// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/Pranc1ngPegasus/trello-kibela-exporter/adapter/configuration"
	"github.com/Pranc1ngPegasus/trello-kibela-exporter/adapter/logger"
	"github.com/Pranc1ngPegasus/trello-kibela-exporter/usecase"
)

// Injectors from inject.go:

func initialize() usecase.ExportKibela {
	config := configuration.Get()
	logrusLogger := logger.Logger()
	exportKibela := usecase.NewExportKibela(config, logrusLogger)
	return exportKibela
}
