// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/Pranc1ngPegasus/trello-kibela-exporter/adapter/configuration"
	"github.com/Pranc1ngPegasus/trello-kibela-exporter/adapter/handler"
	"github.com/Pranc1ngPegasus/trello-kibela-exporter/adapter/logger"
	"github.com/Pranc1ngPegasus/trello-kibela-exporter/usecase"
)

// Injectors from inject.go:

func initialize() handler.TrelloToKibela {
	config := configuration.Get()
	logrusLogger := logger.Logger()
	importTrello := usecase.NewImportTrello(config, logrusLogger)
	getBoardMembers := usecase.NewGetBoardMembers(config, logrusLogger)
	constructMarkdown := usecase.NewConstructMarkdown(logrusLogger)
	exportKibela := usecase.NewExportKibela(config, logrusLogger)
	archiveTrello := usecase.NewArchiveTrello(config, logrusLogger)
	trelloToKibela := handler.NewTrelloToKibela(config, logrusLogger, importTrello, getBoardMembers, constructMarkdown, exportKibela, archiveTrello)
	return trelloToKibela
}
